spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/auth_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: public
    contexts: dev
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE




oauth2:
  clients:
    - clientId: web-client-pkce
      clientSecret: web-client-secret
      redirectUri: http://localhost:4000/auth/callback

      scopes:
        - openid
        - profile
      grantTypes:
          - authorization_code
          - refresh_token

application:
  cors:
    allowed-origins:
      - "http://localhost:4200"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
    allow-credentials: true
    max-age: 3600

server:
  port: 7878